/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microsoft_codepush_react_CodePushUpdateUtils */

#ifndef _Included_com_microsoft_codepush_react_CodePushUpdateUtils
#define _Included_com_microsoft_codepush_react_CodePushUpdateUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microsoft_codepush_react_CodePushUpdateUtils
 * Method:    hdiffPatch
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_microsoft_codepush_react_CodePushUpdateUtils_hdiffPatch
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
